
services:
  my_docker_server:
    build: ../part45/  
    image: myserver:v1
    container_name: my_server
    ports:
      - "8081:81"  

  nginx-proxy:
    image: nginx
    container_name: nginx
    ports:
      - "80:8080"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  

networks:
  default:
    driver: bridge